version: "3"
services:
  neo4j:
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/plugins:/plugins
      - $HOME/neo4j/import:/var/lib/neo4j/import
    environment: 
      NEO4J_AUTH: neo4j/test

  go-restful-api:
    build: ./
    ports:
      - '8080:8080'
    links:
      - neo4j:neo4j
    depends_on:
      - neo4j
    volumes:
      - ./:/app